.\" Process this file with
.\" groff -man -Tutf8 betaradio.1
.\"
.TH BETARADIO 1 "2011-01-04" GNU "BetaRadio User Manuals"
.SH NAME
betaradio \- An easy way to listen to internet radio of Taiwan.
.SH SYNOPSIS
.B betaradio
.SH DESCRIPTION
With this client you can listen to internet radio of Taiwan without opening a
browser. It displays a icon on system tray that you can click and select the
channel you want to listen to.
.SH SEE ALSO
.IR http://code.google.com/p/betaradio/
.SH AUTHOR
Shin-Yuan Lee (FourDollars) <fourdollars@gmail.com>
